steps:
  - label: "Swift ${SWIFT_VERSION} Tests (macOS)"
    command:
      - "swift test --parallel"
      - "swift build --configuration release"
    agents:
      os: "macOS"
    env:
      DEVELOPER_DIR: "/Applications/Xcode_${XCODE_VERSION}.app/Contents/Developer"

    matrix:
      - XCODE_VERSION: "13.2.1"
        SWIFT_VERSION: "5.5"
      - XCODE_VERSION: "13.3.1"
        SWIFT_VERSION: "5.6"

trigger:
  branches: 
    - "main"
