steps:
  - label: "Swift Tests (macOS)"
    command:
      - "swift test --parallel"
      - "swift build --configuration release"
    agents:
      os: "macOS"
    env:
      DEVELOPER_DIR: "/Applications/Xcode.app/Contents/Developer"

trigger:
  branches: 
    - "main"
